config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  resources :sessions

  resources :tasks

  resources :users

  namespace :api, defaults:{format: 'json'} do
    scope module: :v1 do
      resources :tasks
      get 'user'=>'users#show'
    end
  end

  root 'tasks#index'

  get '/sign_up' => 'users#new', as: 'signup'
  get '/login' => 'sessions#new', as: 'login'
  delete '/logout' => 'sessions#destroy', as: 'logout'

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :name, presence: true, uniqueness: true
  validates_presence_of :password

  has_many :tasks
end

app/controllers/api/v1/base_controller.rb
module Api
  module V1
    class BaseController < ApplicationController
      doorkeeper_for :all
      respond_to :json
      private
      def current_user
        @current_user ||= User.find(doorkeeper_token.resource_owner_id)
      end
    end
  end
end

app/controllers/api/v1/tasks_controller.rb
module Api
  module V1
    class TasksController < BaseController
      def index
        respond_with current_user.tasks
      end

      def create
        respond_with current_user.tasks.create(task_params)
      end

      private
      def task_params
        params.require(:task).permit(:name,:user_id)
      end
    end
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::BaseController
  def show
    respond_with current_user.as_json(except: :password_digest)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.find_by_name(params[:name])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice:"Logged in successfully."
    else
      render 'new', alert:'Invalid name or password.'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice:"Logged out successfully."
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :authorize, except: [:index, :show]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all.joins(:user).select('tasks.*, users.name as user_name')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasks }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    @task.user = current_user

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render json: @task, status: :created }
      else
        format.html { render action: 'new' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:user_id, :name)
    end
    def authorize
      redirect_to root_url, alert:'Log in first.' unless current_user
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %title my_353_oauth
    %meta{:content => "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no", :name => "viewport"}
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}

    / Le HTML5 shim, for IE6-8 support of HTML5 elements
    /[if lt IE 9]
      = javascript_include_tag "https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js", "https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .navbar.navbar-inverse.navbar-fixed-top
      .container
        .navbar-header
          %button.navbar-toggle{:type => "button", :data => {:toggle => "collapse", :target => ".navbar-collapse"} }
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to "Project name", "#", :class => "navbar-brand"
        .collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li.active
              %a{:href => "#"} Home
            %li
              %a{:href => "#about"} About
            %li
              %a{:href => "#contact"} Contact
          %ul.nav.navbar-nav.navbar-right
            - if current_user
              %li= link_to "Profile #{current_user.name}", user_path(current_user)
              %li= link_to 'Log Out', logout_path, method: :delete
            - else
              %li= link_to 'Sign Up', signup_path
              %li= link_to 'Log In', login_path
    .container
      - flash.each do |name, msg|
        = content_tag :div, :class => "alert alert-#{%w[alert error].include?(name.to_s) ? "danger" : "success" } alert-dismissable" do
          %button.close{:type => "button", :data => {:dismiss => "alert"}, :aria => {:hidden => "true"} } &times;
          = msg
      = yield

app/views/tasks/_form.html.haml
= simple_form_for(@task) do |f|
  = f.error_notification

  .form-inputs
    = f.association :user
    = f.input :name

  .form-actions
    = f.button :submit

app/views/tasks/edit.html.haml
.page-header
  = link_to tasks_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to @task, :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-info-sign
    Show
  %h1 Editing task

= render 'form'

app/views/tasks/index.html.haml
.page-header
  = link_to new_task_path, :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-plus
    New Task
  %h1 Listing tasks

= simple_form_for Task.new do |f|
  = f.input :name
  = f.submit 'Add'

.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th User
        %th Name
        %th
        %th
        %th

    %tbody
      - @tasks.each do |task|
        %tr
          %td= task.user_name
          %td= task.name
          %td= link_to 'Show', task
          %td= link_to 'Edit', edit_task_path(task)
          %td= link_to 'Destroy', task, :data => { confirm: 'Are you sure?' }, :method => :delete

app/views/tasks/new.html.haml
.page-header
  = link_to tasks_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  %h1 New task

= render 'form'

app/views/tasks/show.html.haml
.page-header
  = link_to tasks_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to edit_task_path(@task), :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-pencil
    Edit
  %h1 Show task

%dl.dl-horizontal
  %dt User:
  %dd= @task.user
  %dt Name:
  %dd= @task.name

app/views/users/_form.html.haml
= simple_form_for(@user) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :password
    = f.input :password_confirmation

  .form-actions
    = f.button :submit

app/views/users/edit.html.haml
.page-header
  = link_to users_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to @user, :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-info-sign
    Show
  %h1 Editing user

= render 'form'

app/views/users/index.html.haml
.page-header
  = link_to new_user_path, :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-plus
    New User
  %h1 Listing users

.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th Name
        %th Password digest
        %th
        %th
        %th

    %tbody
      - @users.each do |user|
        %tr
          %td= user.name
          %td= user.password_digest
          %td= link_to 'Show', user
          %td= link_to 'Edit', edit_user_path(user)
          %td= link_to 'Destroy', user, :data => { confirm: 'Are you sure?' }, :method => :delete

app/views/users/new.html.haml
.page-header
  = link_to users_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  %h1 New user

= render 'form'

= debug @user.to_yaml

app/views/users/show.html.haml
.page-header
  = link_to users_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to edit_user_path(@user), :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-pencil
    Edit
  %h1 Show user

%dl.dl-horizontal
  %dt Name:
  %dd= @user.name
  %dt Password digest:
  %dd= @user.password_digest